version: "3"

services:
  px4-rover:
    build: .
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - ./:/home/px4
      - /tmp/.X11-unix:/tmp/.X11-unix  
        #- /dev:/dev 
      #- /home/dasc/hardik/PX4-Autopilot-Quad:/home/px4
      #- /home/hardik/Desktop/Research/PX4-Autopilot-Quad:/home/px4
    devices:
      - "/dev/ttyACM1:/dev/ttyACM1"
    environment:
            #- NVIDIA_DISABLE_REQUIRE=1
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
        #- NVIDIA_VISIBLE_DEVICES=all
        #- NVIDIA_DRIVER_CAPABILITIES=all
        #runtime: nvidia
        # deploy:
        #resources:
        #reservations:
        #devices:
        #    - driver: nvidia
        #      count: 1
        #      capabilities: [gpu]
