version: "3"

services:
  px4-rover:
    build: .
    privileged: true
    tty: true
    network_mode: "host"
    volumes:
      - /home/dasc/hardik/PX4-Autopilot-Quad:/home/px4
    environment:
            #- NVIDIA_DISABLE_REQUIRE=1
      - DISPLAY=$DISPLAY
        #- NVIDIA_VISIBLE_DEVICES=all
        #- NVIDIA_DRIVER_CAPABILITIES=all
        #runtime: nvidia
        # deploy:
        #resources:
        #reservations:
        #devices:
        #    - driver: nvidia
        #      count: 1
        #      capabilities: [gpu]
